
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Snehal
 */
public class Return_book extends javax.swing.JFrame {

    /**
     * Creates new form Return_book
     */
    public Return_book() {
        initComponents();
        date();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtB_id = new javax.swing.JTextField();
        txtReturnDate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtStud_id = new javax.swing.JLabel();
        txtIssueDate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(490, 200));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Book ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 292, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 344, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Issue Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 406, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Return Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, -1, -1));

        txtB_id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtB_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtB_idActionPerformed(evt);
            }
        });
        getContentPane().add(txtB_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 282, 213, -1));

        txtReturnDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtReturnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 475, 213, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Snehal\\Downloads\\Icon 1\\Icon 1\\return book png.png")); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 556, 103, 51));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red-x-mark-transparent-background-3.png"))); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 556, 127, 51));

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        txtStud_id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtStud_id.setForeground(new java.awt.Color(255, 255, 255));
        txtStud_id.setText("jLabel5");
        getContentPane().add(txtStud_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 344, 213, -1));

        txtIssueDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtIssueDate.setForeground(new java.awt.Color(255, 255, 255));
        txtIssueDate.setText("jLabel7");
        getContentPane().add(txtIssueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 406, 213, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" Return Book");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 260, 61));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newcmn_BG.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

      Connection conn;
    PreparedStatement insert;
    PreparedStatement update;
    ResultSet rs;
    
    
    //--For Current date
    
       public void date()
    {
        
        DateTimeFormatter Dtd = DateTimeFormatter.ofPattern("YYYY/MM/dd");
        LocalDateTime now = LocalDateTime.now();
        String date = Dtd.format(now);
        txtReturnDate.setText(date);
        
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        //---Saving Returned book information to returnbook table
        
         try {                                         
           
            // TODO add your handling code here:
                        conn.setAutoCommit(false);

            String BookID =txtB_id.getText();
            String StudentID =txtStud_id.getText();
            String IssueDate =txtIssueDate.getText();
            String DueDate =txtReturnDate.getText();
                       
  
           
            conn = DriverManager.getConnection("jdbc:mysql://localhost/sailibrary","root","");
            insert = conn.prepareStatement("insert into returnbook(book_id,stud_id,issued_dt,return_dt)values(?,?,?,?)");
            insert.setString(1, BookID);
            insert.setString(2, StudentID);
            insert.setString(3, IssueDate);
            insert.setString(4, DueDate);

            
                insert.executeUpdate();
                     
                      insert = conn.prepareStatement("update issuebook set return_book = 'YES' where stud_id ='"+StudentID+"' and book_id='"+BookID+"'");
                      insert.executeUpdate();
            

            
            JOptionPane.showMessageDialog(this, "Book Returned by " +BookID);
            
            //--For report purpose
            
           
            
            
            
            
        } catch (SQLException ex) {
             try {
                 conn.rollback();
             } catch (SQLException ex1) {
                 Logger.getLogger(Return_book.class.getName()).log(Level.SEVERE, null, ex1);
             }

            
            Logger.getLogger(newStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtB_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtB_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtB_idActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        //--to Search book and student from issue table 
        
        //-----Mine one
              
         
        try {
            // TODO add your handling code here:
            String BookID = txtB_id.getText();
             Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/sailibrary","root","");
            insert = conn.prepareStatement("select book_id,stud_id,issue_dt,returned_book from issuebook where book_id = ?");
            insert.setString(1, BookID);
            rs = insert.executeQuery();
            
            if(rs.next()==false)
            {
                JOptionPane.showMessageDialog(this, "Book Issued details NOT Found");
                setVisible(false);
                new Return_book().setVisible(true);
            }
            else
            {
                String id = rs.getString(1);
                String StudentID = rs.getString(2);
                String IssuDate = rs.getString(3);
             
                
                //--for report purpose
                
               
               txtB_id.setText(id.trim());
                txtStud_id.setText(StudentID.trim());
                txtIssueDate.setText(IssuDate.trim());

                            JOptionPane.showMessageDialog(this, "Book Issued details found");

            }
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Return_book.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Return_book.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         setVisible(false);
            new Home().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Return_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Return_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Return_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Return_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Return_book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtB_id;
    private javax.swing.JLabel txtIssueDate;
    private javax.swing.JTextField txtReturnDate;
    private javax.swing.JLabel txtStud_id;
    // End of variables declaration//GEN-END:variables
}
